# Dockerfile.server
# مرحله ۱: انتخاب یک نسخه سبک از Node.js
FROM node:20-alpine AS base

# نصب curl برای health check (بهتره باشه)
RUN apk --no-cache add curl

# ساختن پوشه کاری برنامه
WORKDIR /app

# کپی فایل‌های پکیج برای نصب وابستگی‌ها
COPY server/package*.json ./

# نصب وابستگی‌های تولید
RUN npm install --production

# کپی مابقی کدهای سرور
COPY server/ .

# اعلام پورت 8080 به داکر
EXPOSE 8080

# اجرای برنامه با Node.js
CMD ["node", "index.js"]
